server:
  port: 50001
  error:
    whitelabel:
      enabled: false
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: abc123456

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
